version: '3.2'
services:
  lizmap:
    image: jancelin/docker-lizmap:3.2.2
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - qgis:/home
     - var:/var/www/websig/lizmap/var
    depends_on:
      - postgis
      - qgiserver
      - redisD
    entrypoint: >
      bash -c "/start.sh"
  qgiserver:
    image: robin0821/qgis-server:3.4
    restart: always
    volumes:
      - qgis:/home  
  redisD:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    entrypoint: >
      bash -c "/docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=dataraft
      - POSTGRES_DBNAME=venus
      - POSTGRES_PASS=Password1234
#      - POSTGRES_DUMP=geopoppy.tar
    volumes:
      - postgres:/var/lib/postgresql
    restart: always
  geoserver:
    image: robin0821/geoserver:2.15
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_PASSWORD=Password1234
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=robin.du@dataraft.com.au
      - PGADMIN_DEFAULT_PASSWORD=Password1234
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer:/data  
  cloud:
    image: coderaiser/cloudcmd:latest-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
      - qgis:/mnt/fs   
  osm2po:
    image: robin0821/osm2po:australia
    restart: on-failure
    ports:
      - 8001:8888
volumes:
   portainer:
   redis:
   qgis:
   var:
   postgres:
   pgadmin4:
   geoserver-data:

   

